### PR TITLE
Makes the logo clickable and sets cursor to pointer when hovering it.

### LINKED ISSUE #64: Click on logo of Jenkins not work
plotpad-client_config__jenkins_

**Page generated: Jul 29, 2015 4:02:48 PMREST APIJenkins ver. 1.622**

### PR DESCRIPTION
**Pull request by Kantis**
Resolves #64

### CODE REVIEW

File: src/logo.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+jQuery(function($) {
+    $('#header .logo').on('click', function() {
+        window.location.href="/";
```
Comment (busches) [inline src/logo.js]: This won't work for anyone that has Jenkins running from a folder, e.g. `blah.com/jenkins`

Comment (Kantis) [inline src/logo.js]: Thanks, fixed :)
